const sql = require('./dbConfig');

// Full permissions list as provided
const permissions = [
  { PermissionKey: 'dashboard', PermissionName: 'Dashboard', ParentKey: null },
  { PermissionKey: 'dashboard_view', PermissionName: 'View', ParentKey: 'dashboard' },
  { PermissionKey: 'users', PermissionName: 'Users', ParentKey: null },
  { PermissionKey: 'user_create', PermissionName: 'Create', ParentKey: 'users' },
  { PermissionKey: 'user_view', PermissionName: 'View', ParentKey: 'users' },
  { PermissionKey: 'user_edit', PermissionName: 'Edit', ParentKey: 'users' },
  { PermissionKey: 'user_delete', PermissionName: 'Delete', ParentKey: 'users' },
  { PermissionKey: 'roles', PermissionName: 'Roles', ParentKey: null },
  { PermissionKey: 'role_create', PermissionName: 'Create', ParentKey: 'roles' },
  { PermissionKey: 'role_view', PermissionName: 'View', ParentKey: 'roles' },
  { PermissionKey: 'role_edit', PermissionName: 'Edit', ParentKey: 'roles' },
  { PermissionKey: 'role_delete', PermissionName: 'Delete', ParentKey: 'roles' },
  { PermissionKey: 'countries', PermissionName: 'Countries', ParentKey: null },
  { PermissionKey: 'country_create', PermissionName: 'Create', ParentKey: 'countries' },
  { PermissionKey: 'country_view', PermissionName: 'View', ParentKey: 'countries' },
  { PermissionKey: 'country_edit', PermissionName: 'Edit', ParentKey: 'countries' },
  { PermissionKey: 'country_delete', PermissionName: 'Delete', ParentKey: 'countries' },
  { PermissionKey: 'states', PermissionName: 'States', ParentKey: null },
  { PermissionKey: 'state_create', PermissionName: 'Create', ParentKey: 'states' },
  { PermissionKey: 'state_view', PermissionName: 'View', ParentKey: 'states' },
  { PermissionKey: 'state_edit', PermissionName: 'Edit', ParentKey: 'states' },
  { PermissionKey: 'state_delete', PermissionName: 'Delete', ParentKey: 'states' },
  { PermissionKey: 'cities', PermissionName: 'Cities', ParentKey: null },
  { PermissionKey: 'city_create', PermissionName: 'Create', ParentKey: 'cities' },
  { PermissionKey: 'city_view', PermissionName: 'View', ParentKey: 'cities' },
  { PermissionKey: 'city_edit', PermissionName: 'Edit', ParentKey: 'cities' },
  { PermissionKey: 'city_delete', PermissionName: 'Delete', ParentKey: 'cities' },
  { PermissionKey: 'regions', PermissionName: 'Regions', ParentKey: null },
  { PermissionKey: 'region_create', PermissionName: 'Create', ParentKey: 'regions' },
  { PermissionKey: 'region_view', PermissionName: 'View', ParentKey: 'regions' },
  { PermissionKey: 'region_edit', PermissionName: 'Edit', ParentKey: 'regions' },
  { PermissionKey: 'region_delete', PermissionName: 'Delete', ParentKey: 'regions' },
  { PermissionKey: 'territories', PermissionName: 'Territories', ParentKey: null },
  { PermissionKey: 'territory_create', PermissionName: 'Create', ParentKey: 'territories' },
  { PermissionKey: 'territory_view', PermissionName: 'View', ParentKey: 'territories' },
  { PermissionKey: 'territory_edit', PermissionName: 'Edit', ParentKey: 'territories' },
  { PermissionKey: 'territory_delete', PermissionName: 'Delete', ParentKey: 'territories' },
  { PermissionKey: 'customer_groups', PermissionName: 'Customer Groups', ParentKey: null },
  { PermissionKey: 'customer_group_create', PermissionName: 'Create', ParentKey: 'customer_groups' },
  { PermissionKey: 'customer_group_view', PermissionName: 'View', ParentKey: 'customer_groups' },
  { PermissionKey: 'customer_group_edit', PermissionName: 'Edit', ParentKey: 'customer_groups' },
  { PermissionKey: 'customer_group_delete', PermissionName: 'Delete', ParentKey: 'customer_groups' },
  { PermissionKey: 'supplier_groups', PermissionName: 'Supplier Groups', ParentKey: null },
  { PermissionKey: 'supplier_group_create', PermissionName: 'Create', ParentKey: 'supplier_groups' },
  { PermissionKey: 'supplier_group_view', PermissionName: 'View', ParentKey: 'supplier_groups' },
  { PermissionKey: 'supplier_group_edit', PermissionName: 'Edit', ParentKey: 'supplier_groups' },
  { PermissionKey: 'supplier_group_delete', PermissionName: 'Delete', ParentKey: 'supplier_groups' },
  { PermissionKey: 'banks', PermissionName: 'Banks', ParentKey: null },
  { PermissionKey: 'bank_create', PermissionName: 'Create', ParentKey: 'banks' },
  { PermissionKey: 'bank_view', PermissionName: 'View', ParentKey: 'banks' },
  { PermissionKey: 'bank_edit', PermissionName: 'Edit', ParentKey: 'banks' },
  { PermissionKey: 'bank_delete', PermissionName: 'Delete', ParentKey: 'banks' },
  { PermissionKey: 'expense_types', PermissionName: 'Expense Types', ParentKey: null },
  { PermissionKey: 'expense_type_create', PermissionName: 'Create', ParentKey: 'expense_types' },
  { PermissionKey: 'expense_type_view', PermissionName: 'View', ParentKey: 'expense_types' },
  { PermissionKey: 'expense_type_edit', PermissionName: 'Edit', ParentKey: 'expense_types' },
  { PermissionKey: 'expense_type_delete', PermissionName: 'Delete', ParentKey: 'expense_types' },
  { PermissionKey: 'services_master', PermissionName: 'Services Master', ParentKey: null },
  { PermissionKey: 'service_master_create', PermissionName: 'Create', ParentKey: 'services_master' },
  { PermissionKey: 'service_master_view', PermissionName: 'View', ParentKey: 'services_master' },
  { PermissionKey: 'service_master_edit', PermissionName: 'Edit', ParentKey: 'services_master' },
  { PermissionKey: 'service_master_delete', PermissionName: 'Delete', ParentKey: 'services_master' },
  { PermissionKey: 'shippers', PermissionName: 'Shippers', ParentKey: null },
  { PermissionKey: 'shipper_create', PermissionName: 'Create', ParentKey: 'shippers' },
  { PermissionKey: 'shipper_view', PermissionName: 'View', ParentKey: 'shippers' },
  { PermissionKey: 'shipper_edit', PermissionName: 'Edit', ParentKey: 'shippers' },
  { PermissionKey: 'shipper_delete', PermissionName: 'Delete', ParentKey: 'shippers' },
  { PermissionKey: 'warehouses', PermissionName: 'Warehouses', ParentKey: null },
  { PermissionKey: 'warehouse_create', PermissionName: 'Create', ParentKey: 'warehouses' },
  { PermissionKey: 'warehouse_view', PermissionName: 'View', ParentKey: 'warehouses' },
  { PermissionKey: 'warehouse_edit', PermissionName: 'Edit', ParentKey: 'warehouses' },
  { PermissionKey: 'warehouse_delete', PermissionName: 'Delete', ParentKey: 'warehouses' },
  { PermissionKey: 'agenda_item_types', PermissionName: 'Agenda Item Types', ParentKey: null },
  { PermissionKey: 'agenda_item_type_create', PermissionName: 'Create', ParentKey: 'agenda_item_types' },
  { PermissionKey: 'agenda_item_type_view', PermissionName: 'View', ParentKey: 'agenda_item_types' },
  { PermissionKey: 'agenda_item_type_edit', PermissionName: 'Edit', ParentKey: 'agenda_item_types' },
  { PermissionKey: 'agenda_item_type_delete', PermissionName: 'Delete', ParentKey: 'agenda_item_types' },
  { PermissionKey: 'meeting_types', PermissionName: 'Meeting Types', ParentKey: null },
  { PermissionKey: 'meeting_type_create', PermissionName: 'Create', ParentKey: 'meeting_types' },
  { PermissionKey: 'meeting_type_view', PermissionName: 'View', ParentKey: 'meeting_types' },
  { PermissionKey: 'meeting_type_edit', PermissionName: 'Edit', ParentKey: 'meeting_types' },
  { PermissionKey: 'meeting_type_delete', PermissionName: 'Delete', ParentKey: 'meeting_types' },
  { PermissionKey: 'locations', PermissionName: 'Locations', ParentKey: null },
  { PermissionKey: 'location_create', PermissionName: 'Create', ParentKey: 'locations' },
  { PermissionKey: 'location_view', PermissionName: 'View', ParentKey: 'locations' },
  { PermissionKey: 'location_edit', PermissionName: 'Edit', ParentKey: 'locations' },
  { PermissionKey: 'location_delete', PermissionName: 'Delete', ParentKey: 'locations' },
  { PermissionKey: 'attendance_status', PermissionName: 'Attendance Status', ParentKey: null },
  { PermissionKey: 'attendance_status_create', PermissionName: 'Create', ParentKey: 'attendance_status' },
  { PermissionKey: 'attendance_status_view', PermissionName: 'View', ParentKey: 'attendance_status' },
  { PermissionKey: 'attendance_status_edit', PermissionName: 'Edit', ParentKey: 'attendance_status' },
  { PermissionKey: 'attendance_status_delete', PermissionName: 'Delete', ParentKey: 'attendance_status' },
  { PermissionKey: 'attendee_types', PermissionName: 'Attendee Types', ParentKey: null },
  { PermissionKey: 'attendee_type_create', PermissionName: 'Create', ParentKey: 'attendee_types' },
  { PermissionKey: 'attendee_type_view', PermissionName: 'View', ParentKey: 'attendee_types' },
  { PermissionKey: 'attendee_type_edit', PermissionName: 'Edit', ParentKey: 'attendee_types' },
  { PermissionKey: 'attendee_type_delete', PermissionName: 'Delete', ParentKey: 'attendee_types' },
  { PermissionKey: 'resolution_status', PermissionName: 'Resolution Status', ParentKey: null },
  { PermissionKey: 'resolution_status_create', PermissionName: 'Create', ParentKey: 'resolution_status' },
  { PermissionKey: 'resolution_status_view', PermissionName: 'View', ParentKey: 'resolution_status' },
  { PermissionKey: 'resolution_status_edit', PermissionName: 'Edit', ParentKey: 'resolution_status' },
  { PermissionKey: 'resolution_status_delete', PermissionName: 'Delete', ParentKey: 'resolution_status' },
  { PermissionKey: 'deductions', PermissionName: 'Deductions', ParentKey: null },
  { PermissionKey: 'deduction_create', PermissionName: 'Create', ParentKey: 'deductions' },
  { PermissionKey: 'deduction_view', PermissionName: 'View', ParentKey: 'deductions' },
  { PermissionKey: 'deduction_edit', PermissionName: 'Edit', ParentKey: 'deductions' },
  { PermissionKey: 'deduction_delete', PermissionName: 'Delete', ParentKey: 'deductions' },
  { PermissionKey: 'incomes', PermissionName: 'Incomes', ParentKey: null },
  { PermissionKey: 'income_create', PermissionName: 'Create', ParentKey: 'incomes' },
  { PermissionKey: 'income_view', PermissionName: 'View', ParentKey: 'incomes' },
  { PermissionKey: 'income_edit', PermissionName: 'Edit', ParentKey: 'incomes' },
  { PermissionKey: 'income_delete', PermissionName: 'Delete', ParentKey: 'incomes' },
  { PermissionKey: 'meetings', PermissionName: 'Meetings', ParentKey: null },
  { PermissionKey: 'meeting_create', PermissionName: 'Create', ParentKey: 'meetings' },
  { PermissionKey: 'meeting_view', PermissionName: 'View', ParentKey: 'meetings' },
  { PermissionKey: 'meeting_edit', PermissionName: 'Edit', ParentKey: 'meetings' },
  { PermissionKey: 'meeting_delete', PermissionName: 'Delete', ParentKey: 'meetings' },
  { PermissionKey: 'customers', PermissionName: 'Customers', ParentKey: null },
  { PermissionKey: 'customer_create', PermissionName: 'Create', ParentKey: 'customers' },
  { PermissionKey: 'customer_view', PermissionName: 'View', ParentKey: 'customers' },
  { PermissionKey: 'customer_edit', PermissionName: 'Edit', ParentKey: 'customers' },
  { PermissionKey: 'customer_delete', PermissionName: 'Delete', ParentKey: 'customers' },
  { PermissionKey: 'suppliers', PermissionName: 'Suppliers', ParentKey: null },
  { PermissionKey: 'supplier_create', PermissionName: 'Create', ParentKey: 'suppliers' },
  { PermissionKey: 'supplier_view', PermissionName: 'View', ParentKey: 'suppliers' },
  { PermissionKey: 'supplier_edit', PermissionName: 'Edit', ParentKey: 'suppliers' },
  { PermissionKey: 'supplier_delete', PermissionName: 'Delete', ParentKey: 'suppliers' },
  { PermissionKey: 'inventory', PermissionName: 'Inventory', ParentKey: null },
  { PermissionKey: 'inventory_view', PermissionName: 'View', ParentKey: 'inventory' },
  { PermissionKey: 'products', PermissionName: 'Products', ParentKey: 'inventory' },
  { PermissionKey: 'product_create', PermissionName: 'Create', ParentKey: 'products' },
  { PermissionKey: 'product_view', PermissionName: 'View', ParentKey: 'products' },
  { PermissionKey: 'product_edit', PermissionName: 'Edit', ParentKey: 'products' },
  { PermissionKey: 'product_delete', PermissionName: 'Delete', ParentKey: 'products' },
  { PermissionKey: 'categories', PermissionName: 'Categories', ParentKey: 'inventory' },
  { PermissionKey: 'category_create', PermissionName: 'Create', ParentKey: 'categories' },
  { PermissionKey: 'category_view', PermissionName: 'View', ParentKey: 'categories' },
  { PermissionKey: 'category_edit', PermissionName: 'Edit', ParentKey: 'categories' },
  { PermissionKey: 'category_delete', PermissionName: 'Delete', ParentKey: 'categories' },
  { PermissionKey: 'units', PermissionName: 'Units', ParentKey: 'inventory' },
  { PermissionKey: 'unit_create', PermissionName: 'Create', ParentKey: 'units' },
  { PermissionKey: 'unit_view', PermissionName: 'View', ParentKey: 'units' },
  { PermissionKey: 'unit_edit', PermissionName: 'Edit', ParentKey: 'units' },
  { PermissionKey: 'unit_delete', PermissionName: 'Delete', ParentKey: 'units' },
  { PermissionKey: 'brands', PermissionName: 'Brands', ParentKey: 'inventory' },
  { PermissionKey: 'brand_create', PermissionName: 'Create', ParentKey: 'brands' },
  { PermissionKey: 'brand_view', PermissionName: 'View', ParentKey: 'brands' },
  { PermissionKey: 'brand_edit', PermissionName: 'Edit', ParentKey: 'brands' },
  { PermissionKey: 'brand_delete', PermissionName: 'Delete', ParentKey: 'brands' },
  { PermissionKey: 'damaged_products', PermissionName: 'Damaged Products', ParentKey: 'inventory' },
  { PermissionKey: 'damaged_product_create', PermissionName: 'Create', ParentKey: 'damaged_products' },
  { PermissionKey: 'damaged_product_view', PermissionName: 'View', ParentKey: 'damaged_products' },
  { PermissionKey: 'damaged_product_edit', PermissionName: 'Edit', ParentKey: 'damaged_products' },
  { PermissionKey: 'damaged_product_delete', PermissionName: 'Delete', ParentKey: 'damaged_products' },
  { PermissionKey: 'goods_receipts', PermissionName: 'Goods Receipts', ParentKey: 'inventory' },
  { PermissionKey: 'goods_receipt_create', PermissionName: 'Create', ParentKey: 'goods_receipts' },
  { PermissionKey: 'goods_receipt_view', PermissionName: 'View', ParentKey: 'goods_receipts' },
  { PermissionKey: 'goods_receipt_edit', PermissionName: 'Edit', ParentKey: 'goods_receipts' },
  { PermissionKey: 'goods_receipt_delete', PermissionName: 'Delete', ParentKey: 'goods_receipts' },
  { PermissionKey: 'goods_issue', PermissionName: 'Goods Issue', ParentKey: 'inventory' },
  { PermissionKey: 'goods_issue_create', PermissionName: 'Create', ParentKey: 'goods_issue' },
  { PermissionKey: 'goods_issue_view', PermissionName: 'View', ParentKey: 'goods_issue' },
  { PermissionKey: 'goods_issue_edit', PermissionName: 'Edit', ParentKey: 'goods_issue' },
  { PermissionKey: 'goods_issue_delete', PermissionName: 'Delete', ParentKey: 'goods_issue' },
  { PermissionKey: 'update_stock', PermissionName: 'Update Stock', ParentKey: 'inventory' },
  { PermissionKey: 'sales', PermissionName: 'Sales', ParentKey: null },
  { PermissionKey: 'sales_view', PermissionName: 'View', ParentKey: 'sales' },
  { PermissionKey: 'sales_create', PermissionName: 'Create', ParentKey: 'sales' },
  { PermissionKey: 'sales_edit', PermissionName: 'Edit', ParentKey: 'sales' },
  { PermissionKey: 'sales_delete', PermissionName: 'Delete', ParentKey: 'sales' },
  { PermissionKey: 'purchasing', PermissionName: 'Purchasing', ParentKey: null },
  { PermissionKey: 'purchasing_view', PermissionName: 'View', ParentKey: 'purchasing' },
  { PermissionKey: 'purchasing_create', PermissionName: 'Create', ParentKey: 'purchasing' },
  { PermissionKey: 'purchasing_edit', PermissionName: 'Edit', ParentKey: 'purchasing' },
  { PermissionKey: 'purchasing_delete', PermissionName: 'Delete', ParentKey: 'purchasing' },
  { PermissionKey: 'services', PermissionName: 'Services', ParentKey: null },
  { PermissionKey: 'services_view', PermissionName: 'View', ParentKey: 'services' },
  { PermissionKey: 'services_create', PermissionName: 'Create', ParentKey: 'services' },
  { PermissionKey: 'services_edit', PermissionName: 'Edit', ParentKey: 'services' },
  { PermissionKey: 'services_delete', PermissionName: 'Delete', ParentKey: 'services' },
  { PermissionKey: 'cash_bank', PermissionName: 'Cash & Bank', ParentKey: null },
  { PermissionKey: 'cash_bank_view', PermissionName: 'View', ParentKey: 'cash_bank' },
  { PermissionKey: 'cash_bank_create', PermissionName: 'Create', ParentKey: 'cash_bank' },
  { PermissionKey: 'cash_bank_edit', PermissionName: 'Edit', ParentKey: 'cash_bank' },
  { PermissionKey: 'cash_bank_delete', PermissionName: 'Delete', ParentKey: 'cash_bank' },
  { PermissionKey: 'financial', PermissionName: 'Financial', ParentKey: null },
  { PermissionKey: 'financial_view', PermissionName: 'View', ParentKey: 'financial' },
  { PermissionKey: 'financial_create', PermissionName: 'Create', ParentKey: 'financial' },
  { PermissionKey: 'financial_edit', PermissionName: 'Edit', ParentKey: 'financial' },
  { PermissionKey: 'financial_delete', PermissionName: 'Delete', ParentKey: 'financial' },
  { PermissionKey: 'hr', PermissionName: 'Human Resources', ParentKey: null },
  { PermissionKey: 'hr_view', PermissionName: 'View', ParentKey: 'hr' },
  { PermissionKey: 'employees', PermissionName: 'Employees', ParentKey: 'hr' },
  { PermissionKey: 'employee_create', PermissionName: 'Create Emp', ParentKey: 'employees' },
  { PermissionKey: 'employee_view', PermissionName: 'View Emp', ParentKey: 'employees' },
  { PermissionKey: 'employee_edit', PermissionName: 'Edit Emp', ParentKey: 'employees' },
  { PermissionKey: 'employee_delete', PermissionName: 'Delete Emp', ParentKey: 'employees' },
  { PermissionKey: 'departments', PermissionName: 'Departments', ParentKey: 'hr' },
  { PermissionKey: 'department_create', PermissionName: 'Create', ParentKey: 'departments' },
  { PermissionKey: 'department_view', PermissionName: 'View', ParentKey: 'departments' },
  { PermissionKey: 'department_edit', PermissionName: 'Edit', ParentKey: 'departments' },
  { PermissionKey: 'department_delete', PermissionName: 'Delete', ParentKey: 'departments' },
  { PermissionKey: 'designations', PermissionName: 'Designations', ParentKey: 'hr' },
  { PermissionKey: 'designation_create', PermissionName: 'Create', ParentKey: 'designations' },
  { PermissionKey: 'designation_view', PermissionName: 'View', ParentKey: 'designations' },
  { PermissionKey: 'designation_edit', PermissionName: 'Edit', ParentKey: 'designations' },
  { PermissionKey: 'designation_delete', PermissionName: 'Delete', ParentKey: 'designations' },
  { PermissionKey: 'attendance', PermissionName: 'Attendance', ParentKey: 'hr' },
  { PermissionKey: 'attendance_create', PermissionName: 'Create', ParentKey: 'attendance' },
  { PermissionKey: 'attendance_view', PermissionName: 'View', ParentKey: 'attendance' },
  { PermissionKey: 'attendance_edit', PermissionName: 'Edit', ParentKey: 'attendance' },
  { PermissionKey: 'attendance_delete', PermissionName: 'Delete', ParentKey: 'attendance' },
  { PermissionKey: 'payroll', PermissionName: 'Payroll', ParentKey: 'hr' },
  { PermissionKey: 'payroll_create', PermissionName: 'Create', ParentKey: 'payroll' },
  { PermissionKey: 'payroll_view', PermissionName: 'View', ParentKey: 'payroll' },
  { PermissionKey: 'payroll_edit', PermissionName: 'Edit', ParentKey: 'payroll' },
  { PermissionKey: 'payroll_delete', PermissionName: 'Delete', ParentKey: 'payroll' },
  { PermissionKey: 'reports', PermissionName: 'Reports', ParentKey: null },
  { PermissionKey: 'reports_create', PermissionName: 'Create', ParentKey: 'reports' },
  { PermissionKey: 'reports_view', PermissionName: 'View', ParentKey: 'reports' },
  { PermissionKey: 'reports_edit', PermissionName: 'Edit', ParentKey: 'reports' },
  { PermissionKey: 'reports_delete', PermissionName: 'Delete', ParentKey: 'reports' },
  { PermissionKey: 'settings', PermissionName: 'Settings', ParentKey: null },
  { PermissionKey: 'currencies', PermissionName: 'Currencies', ParentKey: null },
  { PermissionKey: 'currency_create', PermissionName: 'Create', ParentKey: 'currencies' },
  { PermissionKey: 'currency_view', PermissionName: 'View', ParentKey: 'currencies' },
  { PermissionKey: 'currency_edit', PermissionName: 'Edit', ParentKey: 'currencies' },
  { PermissionKey: 'currency_delete', PermissionName: 'Delete', ParentKey: 'currencies' },
  { PermissionKey: 'languages', PermissionName: 'Languages', ParentKey: null },
  { PermissionKey: 'language_create', PermissionName: 'Create', ParentKey: 'languages' },
  { PermissionKey: 'language_view', PermissionName: 'View', ParentKey: 'languages' },
  { PermissionKey: 'language_edit', PermissionName: 'Edit', ParentKey: 'languages' },
  { PermissionKey: 'language_delete', PermissionName: 'Delete', ParentKey: 'languages' },
];

async function seedPermissions() {
  try {
    // Ensure connection is open
    if (!sql.connected) {
      await sql.connect();
    }
    for (const perm of permissions) {
      await sql.query`
        IF NOT EXISTS (SELECT 1 FROM Permissions WHERE PermissionKey = ${perm.PermissionKey})
        INSERT INTO Permissions (PermissionKey, Name, ParentKey, IsActive)
        VALUES (${perm.PermissionKey}, ${perm.PermissionName}, ${perm.ParentKey}, 1)
      `;
    }
    console.log('✅ All permissions seeded.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Error seeding permissions:', err.message || err);
    process.exit(1);
  }
}

seedPermissions();
